spring:
  datasource:
    druid:
      url: jdbc:mysql://47.102.130.18:3306/music_recommend_system?characterEncoding=utf8&setTimezone=Asia/Shanghai&useAffectedRows=true
      username: root
      password: 123
      initial-size: 1
      max-active: 20
      max-wait: 6000
      min-idle: 1
  redis:
    host: 47.102.130.18
    password: 123
    lettuce:
      shutdown-timeout: 300

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080
